---
title: "salmon_agmaps_loopoutput"
author: "Sydney Schmitter"
date: "7/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::knit_meta(class=NULL, clean = TRUE)
# Clear existing environment
rm(list = ls())
# Load libraries
library(cdlTools)
library(raster)
library(tidyverse)
library(ggthemes)
library(janitor)
library(sf)
library(stars)
library(ggspatial)
library(tmap)
library(units)
library(tabularaster)
library(cowplot)
library(knitr)
library(kableExtra)
library(here)


# Set ggplot2 themes
theme_set(theme_clean())
theme_update(
  plot.background = element_rect(color = NA),
  plot.title.position = "plot",
  plot.caption.position = "plot"
)
# Set top-level working directory
setwd("~/Desktop/Github Repo/salmon_ag")
```

## Agricultural land use in salmon habitat

This document summarizes land cover over the habitat range of listed salmonid populations on the West Coast, with a focus on agriculture. Included are land cover summaries for 30 Distinct Population Segments (DPS).

```{r data-prep, echo=FALSE, message=FALSE, include=FALSE}
# Get CDL data, process outlined on recreationsalmonag.Rmd
CDLwest = raster('cdl_west.tif')

#clean up recovery domain names, simplify naming of targeted species to summarize
sf_recoverydomain <- st_read(here("data/recovery_subdomains/subdomains-ver7.shp")) %>% clean_names()
sf_recoverydomain <-
  sf_recoverydomain %>%
  distinct(.keep_all = TRUE) %>%
  dplyr::filter(`class` == "Accessible") %>%
  select(-class, -sourcethm) %>%
  mutate(
    species2 = case_when(
      species == "Steelhead" ~ "Steelhead",
      str_detect(species, "Chinook") ~ "Chinook",
      str_detect(species, "Chum") ~ "Chum",
      str_detect(species, "Pink") ~ "Pink",
      TRUE ~ species
    ),
    species3 = case_when(
      species == "Steelhead" ~ "Trout",
      TRUE ~ "Salmon"
    ),
    domain = case_when(
      subdomain == "Washington Coast" ~ "Puget Sound",
      subdomain == "Snake River" ~ "Interior Columbia",
      subdomain == "Middle Columbia River" ~ "Interior Columbia",
      subdomain == "Upper Columbia River" ~ "Interior Columbia",
      subdomain == "Lower Columbia River" ~ "Willamette/Lower Columbia",
      subdomain == "Upper Willamette River" ~ "Willamette/Lower Columbia",
      subdomain == "California Central Valley" ~ "Central Valley",
      subdomain == "North-Central California Coast" ~ "North-Central California Coast",
      TRUE ~ subdomain
    ),
    area = st_area(geometry),
    area = set_units(area, km^2)
  ) %>%
  st_transform(CDLwest@crs)

#Need cleaned csv
df_crdcount <- read_csv(here("data_subdomains_2021.csv"))

states_core <- 
  st_as_sf(maps::map("state", regions = c("california", "oregon", "washington", "idaho"), plot = FALSE, fill = TRUE)) %>%
  st_transform(st_crs(sf_recoverydomain))
states_expand <-
  st_as_sf(
    maps::map(
      "state", 
      regions = 
        c(
          "california", 
          "oregon", 
          "washington", 
          "idaho", 
          "montana", 
          "wyoming",
          "arizona",
          "nevada",
          "utah",
          "colorado",
          "new mexico"
        ), plot = FALSE, fill = TRUE)
  ) %>% st_transform(st_crs(sf_recoverydomain))
land <- st_as_sf(maps::map("world", regions = c("Canada", "Mexico"), plot = FALSE, fill = TRUE)) %>% st_transform(st_crs(sf_recoverydomain))
```

```{r lapply, echo=FALSE}
# List of distinct population segments
dps <- df_crdcount %>% distinct(esu_dps) %>% arrange(esu_dps) %>% pull(esu_dps)
sort(dps)
dps <- dps[1:37]

invisible(
  for (i in dps) { 
           cat("  \n###", i)
           cat("  \n**Status:**", df_crdcount %>% filter(esu_dps == i) %>% pull(status))
           cat("  \n**Domain:**", df_crdcount %>% filter(esu_dps == i) %>% pull(domain))
           cat("  \n")
           
           #Plot the agricultural land uses inside each area
          border <- sf_recoverydomain %>% 
              arrange(esu_dps) %>% 
              slice(i)
           
           clip1 <- raster::crop(CDLwest, extent(border)) # Clip cdl to rectangle extents of the polygon
           clip2 <- mask(clip1, border) # Mask cdl to only what's within polygon
           
           
           df_clip2 <- as.data.frame(clip2, xy = TRUE)
           df_clip2 <- df_clip2 %>% 
             drop_na(cdl_west) %>% 
             mutate(cdl_west = updateNamesCDL(cdl_west))
           
           types <- df_clip2  %>%
             group_by(cdl_west)  %>%
             count
           types <- types %>%
             mutate(
               cropgroup = 
                 case_when(
                   str_detect(cdl_west, "Barley|Rye|Wheat|Oats|Triticale|Sorghum|Buckwheat|Millet|Dbl") ~ "smgrains",
                   str_detect(cdl_west, "Walnuts|Almonds|Pecans|Pistachios") ~ "nuts" ,
                   str_detect(cdl_west, "Apples  | Apricots|berries|  Cantaloupes|Cherries|Citrus|Watermelons|Melons|Nectarines|Oranges|Peaches|Pears|Plums|Pomegranates|Other Tree|Olives") ~ "fruits",
                   str_detect(cdl_west, "Tomatoes|Asparagus|Broccoli|Cabbage|Carrots|Cauliflower|Cucumbers|Garlic|Gourds|Greens|Lettuce|Onions|Peas|Peppers|Popcorn|Pumpkins|Radish|Squash|Sweet Corn|Sweet Potatoes|Turnips") ~ "vegetables",
                    str_detect(cdl_west, "Chick Peas|Christmas Trees|Dry Beans|Flaxseed|Herbs|Hops|Lentils|Mint|Misc Vegs|Mustard|Other Crops|Rape|Safflower|Sod/Grass Seed|Sugarbeets|Sunflower|Vetch") ~ "other_crops",
                   str_detect(cdl_west,  "Alfalfa|Other Hay") ~ "hay",
                   str_detect(cdl_west,  "Rice") ~ "rice",
                   str_detect(cdl_west,  "Cotton") ~ "cotton",
                   str_detect(cdl_west,  "Fallow") ~ "fallow",
                   str_detect(cdl_west,  "Grapes") ~ "grapes",
                   str_detect(cdl_west,  "Pasture")~ "pasture",
                   TRUE ~ "other")
             )
           types$cropgroup <- if_else(types$cdl_west == "Potatoes", "potatoes", types$cropgroup)
           types$cropgroup <- if_else(types$cdl_west == "Corn", "corn", types$cropgroup)
           types$cropgroup <- if_else(types$cdl_west == "Open Water", "Open Water", types$cropgroup)
           # Join types to the land use data frame
           df_clip2_types = left_join(df_clip2, types)
           df_clip2_types 
           
           setwd("C:/Users/Lisa.Pfeiffer/Documents/GitHub/salmon_ag/output/salmonid_ag_maps/")
           fname <- dps[i]
           fname1 <- paste0(fname, ".pdf")
           pdf(file = fname1, width = 6, height = 4.5)
           
           p_ag_cover <- ggplot() +
             geom_raster(data = df_clip2_types, aes(x = x, y = y, fill = cropgroup)) +
             scale_fill_manual(
                "Land cover (CDL2021)",
      limits = c( "corn", "cotton", "fallow", "fruits", "grapes","hay","other_crops", "nuts",  "pasture", "potatoes", "rice", "smgrains",  "vegetables", "Open Water", "other"),
      labels = c("Corn", "Cotton", "Fallow", "Fruits", "Grapes","Hay","Other Crops", "Nuts", "Pasture", "Potatoes", "Rice", "Small Grains",  "Vegetables", "Open Water", "Other"),
      values = c( "darkgoldenrod", "goldenrod", "grey", "darkred", "purple", "lightgreen", "gold", "tan", "darkgreen", "black", "violet","pink",  "springgreen3", "darkblue", "antiquewhite1")) +
  
             ggtitle(i) +
             theme_map()
        plot(p_ag_cover)
        dev.off()
         }
  )

```
