---
title: "spawninghabitatmapping"
author: "Sydney Schmitter"
date: "7/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(cdlTools)
library(raster)
library(tidyverse)
library(janitor)
library(sf)
library(stars)
library(ggspatial)
library(tmap)
library(units)
library(tabularaster)
library(osmdata)
library(here)
library(exactextractr)
library(CropScapeR)
library(foreign)
library(ggthemes)
library(knitr)
library(nhdR)
library(raster)
library(rgdal)
library(rgeos)

# Set ggplot2 themes
theme_set(theme_clean())
theme_update(
  plot.background = element_rect(color = NA),
  plot.title.position = "plot",
  plot.caption.position = "plot"
)

# Load CDL key
data("linkdata")

setwd("~/Desktop/Github Repo/salmon_ag")
```

```{r cars}
#plot spawning and rearing habitat with CDL data
CDLwest = raster('cdl_west.tif')

(sf_recoverydomain_use <- st_read(here("data/huc6_esu-withadds-ver5-alb27.shp")) %>% clean_names()) %>% names

# sf_recoverydomain_points <- as.data.frame(sf_recoverydomain_use, xy = TRUE)
# 
# domainraster <- raster(sf_recoverydomain_use)

sf_recoverydomain_use_r_ch_fa <-
  sf_recoverydomain_use %>%
  filter(!is.na(r_ch_fa)) %>%
  select(c(objectid:states), r_ch_fa, c(regime01b:r_ch03_c), geometry) %>%
  bind_cols(
    tibble("hab_use" = sf_recoverydomain_use %>%
             st_drop_geometry() %>%
             filter(!is.na(r_ch_fa)) %>%
             select(sp_l_chfa:mi_l_chfa) %>%
             as.matrix() %*% 1:3)
  ) %>%
  mutate(
    hab_use = case_when(hab_use == 0 ~ NA_real_, TRUE ~ hab_use),
    hab_use = factor(hab_use, levels = c(1, 2, 3), labels = c("spawn+rearing", "rearing+migration", "migration")),
  ) %>%
  st_transform(CDLwest@crs)

sf_recoverydomain_use_r_ch_fa <- filter(sf_recoverydomain_use_r_ch_fa, hab_use == c("rearing+migration", "migration"))
sf_snakefallchinook <- filter(sf_recoverydomain_use_r_ch_fa, r_ch_fa == "Snake River Fall-run Chinook Salmon")
sf_snakefallchinook <- subset(sf_snakefallchinook, select = c(r_ch_fa, geometry, hab_use))
st_write(sf_snakefallchinook, "sf_snakefallchinookmigration.shp")

states_core <-
  st_as_sf(maps::map("state", regions = c("california", "oregon", "washington", "idaho"), plot = FALSE, fill = TRUE)) %>%
  st_transform(st_crs(sf_snakefallchinook))
states_expand <-
  st_as_sf(
    maps::map(
      "state",
      regions =
        c(
          "california",
          "oregon",
          "washington",
          "idaho",
          "montana",
          "wyoming",
          "arizona",
          "nevada",
          "utah",
          "colorado",
          "new mexico"
        ), plot = FALSE, fill = TRUE)
  ) %>% st_transform(st_crs(sf_snakefallchinook))
land <- st_as_sf(maps::map("world", regions = c("Canada", "Mexico"), plot = FALSE, fill = TRUE)) %>% st_transform(st_crs(sf_snakefallchinook))

clip1 <- raster::crop(CDLwest, extent(sf_snakefallchinook)) # Clip cdl to rectangle extents of the polygon
clip2 <- mask(clip1, sf_snakefallchinook) # Mask cdl to only what's within polygon

writeRaster(clip2, filename= "sfchinookCDL.tif")

df_clip2_pts <- as.data.frame(clip2, xy = TRUE)

 lkup <- data.frame(col = c('index', 'value'), ind = rep(1:(length(cdlTools::varNamesCDL)/2), each = 2), cdl_west_new = cdlTools::varNamesCDL) %>%
   pivot_wider(names_from = 'col', values_from = 'cdl_west_new') %>%
   mutate(index = as.numeric(index)) %>%
   select(-ind)

 df_clip2 <- df_clip2_pts %>% 
   left_join(lkup, by = c('cdl_west' = 'index')) %>%
   select(-cdl_west) %>%
   rename(cdl_west = value)

types <- df_clip2  %>%
  group_by(cdl_west)  %>%
  count

types <- types %>%
  mutate(
    cropgroup =
      case_when(
        str_detect(cdl_west, "Barley|Rye|Wheat|Oats|Triticale|Sorghum|Buckwheat|Millet|Dbl") ~ "smgrains",
        str_detect(cdl_west, "Walnuts|Almonds|Pecans|Pistachios") ~ "nuts" ,
        str_detect(cdl_west, "Apples  | Apricots|berries|  Cantaloupes|Cherries|Citrus|Watermelons|Melons|Nectarines|Oranges|Peaches|Pears|Plums|Pomegranates|Other Tree|Olives") ~ "fruits",
        str_detect(cdl_west, "Tomatoes|Asparagus|Broccoli|Cabbage|Carrots|Cauliflower|Cucumbers|Garlic|Gourds|Greens|Lettuce|Onions|Peas|Peppers|Popcorn|Pumpkins|Radish|Squash|Sweet Corn|Sweet Potatoes|Turnips") ~ "vegetables",
        str_detect(cdl_west, "Chick Peas|Christmas Trees|Dry Beans|Flaxseed|Herbs|Hops|Lentils|Mint|Misc Vegs|Mustard|Other Crops|Rape|Safflower|Sod/Grass Seed|Sugarbeets|Sunflower|Vetch") ~ "other_crops",
        str_detect(cdl_west,  "Alfalfa|Other Hay") ~ "hay",
        str_detect(cdl_west,  "Rice") ~ "rice",
        str_detect(cdl_west,  "Cotton") ~ "cotton",
        str_detect(cdl_west,  "Fallow") ~ "fallow",
        str_detect(cdl_west,  "Grapes") ~ "grapes",
        str_detect(cdl_west,  "Pasture")~ "pasture",
        TRUE ~ "other")
  )
types$cropgroup <- if_else(types$cdl_west == "Potatoes", "potatoes", types$cropgroup)
types$cropgroup <- if_else(types$cdl_west == "Corn", "corn", types$cropgroup)
types$cropgroup <- if_else(types$cdl_west == "Open Water", "Open Water", types$cropgroup)
          
df_clip2_types = left_join(df_clip2, types) 
dfl <- rasterFromXYZ(df_clip2_types)
writeRaster(dfl, filename="CDLsfchinook.tif")

edat <- mutate(df_clip2_types, cropgroup = ifelse(!is.na(cropgroup), cropgroup, 'missing'))
rasterFromXYZ(edat)

#fname <- dps[i]
fname1 <- "trialspawn.pdf"
pdf(file = fname1, width = 7, height = 5.5)

ggplot() +
   geom_raster(data = edat, aes(x = x, y = y, fill = cropgroup, group = cropgroup)) +
   scale_fill_manual(
     limits = c( "nuts", "smgrains", "fruit", "hay", "potatoes", "rice", "cotton", "fallow", "grapes", "veg", "corn", "othercrops", "Open Water", "Pasture", "other", "missing"),
     labels = c( "Nuts", "Small grains", "Fruit", "Hay", "Potatoes", "Rice", "Cotton", "Fallow cropland", "Grapes", "Vegetables", "Corn", "Other crops", "Open Water", "Pasture", "other", "missing"),
     values = c( "darkgoldenrod", "goldenrod", "darkred", "darkgreen", "black",  "violet","pink", "grey", "purple", "lightgreen", "gold", "lightblue", "darkblue", "springgreen3", "antiquewhite1", "dark grey"))

dev.off()
#  
#  
# dps <- df_crdcount %>% distinct(esu_dps) %>% arrange(esu_dps) %>% pull(esu_dps)
# sort(dps)
# i = 4
# 
# border <- sf_recoverydomain %>%
#    arrange(esu_dps) %>%
#    slice(i)
# 
# clip1 <- raster::crop(CDLwest, extent(border)) # Clip cdl to rectangle extents of the polygon
# clip2 <- mask(clip1, border) # Mask cdl to only what's within polygon
# 
# df_clip2_pts <- as.data.frame(clip2, xy = TRUE)
# 
# # rearrange the varNamesCDL into a data frame that can be merged onto the df_clip2
#  lkup <- data.frame(col = c('index', 'value'), ind = rep(1:(length(cdlTools::varNamesCDL)/2), each = 2), cdl_west_new = cdlTools::varNamesCDL) %>%
#    pivot_wider(names_from = 'col', values_from = 'cdl_west_new') %>%
#    mutate(index = as.numeric(index)) %>%
#    select(-ind)
#  
#   # join the names
#  df_clip2 <- df_clip2_pts %>% 
#    left_join(lkup, by = c('cdl_west' = 'index')) %>%
#    select(-cdl_west) %>%
#    rename(cdl_west = value)

```

```{r pressure, echo=FALSE}
NHDwaterbody <- read_sf(here("NHDWashington/Shape/NHDWaterbody.shp")) 

NHDwaterbody_NAD83 <- st_transform(NHDwaterbody, crs(sf_snakefallchinook))

clip3 <- sf::st_intersection(NHDwaterbody_NAD83, sf_snakefallchinook)

st_write(clip3, "clip3.shp")

NHDwaterbodyidaho <- read_sf(here("NHDIdaho/Shape/NHDWaterbody.shp")) 

NHDwaterbodyidaho_NAD83 <- st_transform(NHDwaterbodyidaho, crs(sf_snakefallchinook))
NHDwaterbodyidaho_NAD83 <- st_zm(NHDwaterbodyidaho_NAD83)
clip3 <- sf::st_intersection(NHDwaterbodyidaho_NAD83, sf_snakefallchinook)

st_write(clip3, "NHDwaterbodyidaho_NAD83.shp")



# Flowline Types
# 46003 = stream/river (intermittent)
# 55800 = artificial path
# 46006 = stream/river (perennial)
# 46007 = stream/river (ephemeral)

#Filter for intermittent streams
#Filter for artificial pahs
#Filter for 


NHDflowline0 <- read_sf(here("NHDWashington/Shape/NHDFlowline_0.shp")) 

NHDflowline0washington_NAD83 <- st_transform(NHDflowline0, crs(sf_snakefallchinook))
NHDflowline0washington_NAD83 <- st_zm(NHDflowline0washington_NAD83)

flowline0clipwashington <- sf::st_intersection(NHDflowline0washington_NAD83, sf_snakefallchinook)

st_write(flowline0clip, "flowline0clip.shp")


NHDflowline0idaho <- read_sf(here("NHDIdaho/Shape/NHDFlowline_0.shp")) 

NHDflowline0idaho_NAD83 <- st_transform(NHDflowline0idaho, crs(sf_snakefallchinook))
NHDflowline0idaho_NAD83 <- st_zm(NHDflowline0idaho_NAD83)

flowline0clipidaho <- sf::st_intersection(NHDflowline0idaho_NAD83, sf_snakefallchinook)

st_write(flowline0clip, "flowline0clipidaho.shp")

NHDflowline0oregon <- read_sf(here("NHDOregon/Shape/NHDFlowline_0.shp")) 

NHDflowline0oregon_NAD83 <- st_transform(NHDflowline0oregon, crs(sf_snakefallchinook))
NHDflowline0oregon_NAD83 <- st_zm(NHDflowline0oregon_NAD83)

flowline0cliporegon <- sf::st_intersection(NHDflowline0oregon_NAD83, sf_snakefallchinook)

st_write(flowline0clip, "flowline0cliporegon.shp")


NHDflowline1 <- read_sf(here("NHDWashington/Shape/NHDFlowline_1.shp")) 

NHDflowline1_NAD83washington <- st_transform(NHDflowline1, crs(sf_snakefallchinook))
NHDflowline1_NAD83washington <- st_zm(NHDflowline1_NAD83washington)

flowline1clipwashington <- sf::st_intersection(NHDflowline1_NAD83washington, sf_snakefallchinook)

st_write(flowline1clipwashington, "flowline1clipwashington.shp")

NHDflowline1idaho <- read_sf(here("NHDIdaho/Shape/NHDFlowline_1.shp")) 

NHDflowline1idaho_NAD83 <- st_transform(NHDflowline1idaho, crs(sf_snakefallchinook))
NHDflowline1idaho_NAD83 <- st_zm(NHDflowline1idaho_NAD83)

flowline1clipidaho <- sf::st_intersection(NHDflowline1idaho_NAD83, sf_snakefallchinook)

st_write(flowline1clip, "flowline1clipidaho.shp")

NHDflowline1oregon <- read_sf(here("NHDOregon/Shape/NHDFlowline_1.shp")) 

NHDflowline1oregon_NAD83 <- st_transform(NHDflowline1oregon, crs(sf_snakefallchinook))
NHDflowline1oregon_NAD83 <- st_zm(NHDflowline1oregon_NAD83)

flowline1cliporegon <- sf::st_intersection(NHDflowline1oregon_NAD83, sf_snakefallchinook)

st_write(flowline1cliporegon, "flowline1cliporegon1.shp")

NHDflowline2 <- read_sf(here("NHDWashington/Shape/NHDFlowline_2.shp")) 

NHDflowline2_NAD83 <- st_transform(NHDflowline2, crs(sf_snakefallchinook))
NHDflowline2_NAD83 <- st_zm(NHDflowline2_NAD83)

flowline2clipwashington <- sf::st_intersection(NHDflowline2_NAD83, sf_snakefallchinook)

st_write(flowline2clip, "flowline2clip.shp")

NHDflowline2 <- read_sf(here("NHDOregon/Shape/NHDFlowline_2.shp")) 

NHDflowline2oregon_NAD83 <- st_transform(NHDflowline2, crs(sf_snakefallchinook))
NHDflowline2oregon_NAD83 <- st_zm(NHDflowline2oregon_NAD83)

flowline2cliporegon <- sf::st_intersection(NHDflowline2oregon_NAD83, sf_snakefallchinook)

st_write(flowline2clip, "flowline2clip.shp")

NHDflowline2 <- read_sf(here("NHDIdaho/Shape/NHDFlowline_2.shp")) 

NHDflowline2idaho_NAD83 <- st_transform(NHDflowline2, crs(sf_snakefallchinook))
NHDflowline2idaho_NAD83 <- st_zm(NHDflowline2idaho_NAD83)

flowline2clipidaho <- sf::st_intersection(NHDflowline2idaho_NAD83, sf_snakefallchinook)

st_write(flowline2clip, "flowline2clip.shp")

flowlineall <- read_csv("flowlineall.csv")

flowlineclip0washington <- st_read("flowline0clip.shp")
flowlineclip0oregon <- st_read("flowline0cliporegon2.shp")
flowlineclip0idaho <- st_read("flowline0clipidaho.shp")
flowlineclip1washington <- st_read("flowline1clip.shp")
flowlineclip1oregon <- st_read("flowline1cliporegon1.shp")
flowlineclip1idaho <- st_read("flowline1clipidaho.shp")
flowlineclip2washington <- st_read("flowline2clip.shp")
flowlineclip2oregon <- st_read("flowline2cliporegon.shp")
flowlineclip3oregon <- st_read("flowline3cliporegon.shp")

flowlineall <- rbind(flowlineclip0washington,flowlineclip0oregon,flowlineclip0idaho,flowlineclip1washington,flowlineclip1oregon,flowlineclip1oregon,flowlineclip1idaho,flowlineclip2washington,flowlineclip2oregon,flowlineclip3oregon)

st_write(flowlineall, "flowlineallwoo.shp")

#intermittentstreams

intermittentstreams <- subset(flowlineall, fcode == "46003")
st_write(intermittentstreams, "intermittentstreams.shp")


ggplot() +
   geom_raster(data = edat, aes(x = x, y = y, fill = cropgroup, group = cropgroup)) +
   scale_fill_manual(
     limits = c( "nuts", "smgrains", "fruit", "hay", "potatoes", "rice", "cotton", "fallow", "grapes", "veg", "corn", "othercrops", "Open Water", "Pasture", "other", "missing"),
     labels = c( "Nuts", "Small grains", "Fruit", "Hay", "Potatoes", "Rice", "Cotton", "Fallow cropland", "Grapes", "Vegetables", "Corn", "Other crops", "Open Water", "Pasture", "other", "missing"),
     values = c( "darkgoldenrod", "goldenrod", "darkred", "darkgreen", "black",  "violet","pink", "grey", "purple", "lightgreen", "gold", "lightblue", "darkblue", "springgreen3", "antiquewhite1")) 
#Clip flowline data to spawning and rearing habitat for California Coastal Chinook Salmon


# NHDflowlines <- subset(NHDflowlines, select = -c(ftype, fcode, mainpath, innetwork, visibility, layer, lengthkm, flowdir))
# 
# NHDwaterbody <- subset(NHDwaterbody, select = -c(ftype, fcode, gnis_id, gnis_name, visibility, objectID))
# 
# NHDwashingtonwater <- rbind(NHDwaterbody, NHDflowlines)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
